import{a as m,S as B,i as n}from"./assets/vendor-BK_rxH-O.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const u of a.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function r(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(o){if(o.ep)return;o.ep=!0;const a=r(o);fetch(o.href,a)}})();m.defaults.baseURL="https://pixabay.com/api/";async function h(t,e=1,r=15){try{return(await m.get("/",{params:{key:"51491215-b07c5a52c3d96c7bcc8c26318",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:r}})).data}catch(i){throw console.error("Error fetching images:",i),i}}let s=null;function q(t){return t.map(e=>`
      <li class="gallery-item">
        <div class="image-wrap">
          <a href="${e.largeImageURL}" data-lightbox="gallery" data-title="${e.tags}">
            <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          </a>
        </div>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${e.likes}</p>
          <p class="info-item"><b>Views</b> ${e.views}</p>
          <p class="info-item"><b>Comments</b> ${e.comments}</p>
          <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
        </div>
      </li>
    `).join("")}function S(t){t.innerHTML=""}function R(){return s||(s=new B(".gallery a",{captionsData:"alt",captionDelay:250})),s}function y(t,e){const r=q(e);t.insertAdjacentHTML("beforeend",r),s?s.refresh():s=R()}function b(){document.querySelector(".loader").style.display="block"}function w(){document.querySelector(".loader").style.display="none"}function L(){const t=document.querySelector(".load-page-btn");t&&(t.style.display="block")}function f(){const t=document.querySelector(".load-page-btn");t&&(t.style.display="none")}const C=document.querySelector(".form"),p=C.querySelector('input[name="search-text"]'),c=document.querySelector(".gallery"),E=document.querySelector(".load-page-btn");let g="",l=1;const d=15;let v=0;C.addEventListener("submit",async t=>{t.preventDefault();const e=p.value.trim();if(e===""){n.warning({title:"",message:"Please enter something in the search field",position:"topRight",backgroundColor:"#ffa000",color:"white",progressBarColor:"#bb7b10",timeout:3e3});return}g=e,l=1,p.value="",S(c),f(),b();try{const r=await h(g,l,d),i=r.hits;v=r.totalHits,i.length===0?n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",color:"white",progressBarColor:"#b51b1b",timeout:3e3}):(y(c,i),r.totalHits>d&&L())}catch{n.error({title:"Error",message:"Сталася помилка при завантаженні зображень. Будь ласка, спробуйте пізніше.",position:"topRight",backgroundColor:"#ef4040",color:"white",progressBarColor:"#b51b1b",timeout:3e3})}finally{w()}});E.addEventListener("click",async()=>{l++,b(),f();try{const e=(await h(g,l,d)).hits;y(c,e,!1);const r=c.firstElementChild;if(r){const o=r.getBoundingClientRect().height;window.scrollBy({top:o*2.1,behavior:"smooth"})}l*d>=v?(f(),n.warning({message:"You have reached the end of the gallery for this query.",position:"topRight",backgroundColor:"#ffa000",color:"white",progressBarColor:"#bb7b10",timeout:3e3})):L()}catch{n.error({message:"Error loading more images.",position:"topRight",backgroundColor:"#ef4040",color:"white",progressBarColor:"#b51b1b",timeout:3e3})}finally{w()}});
//# sourceMappingURL=index.js.map
