import{a as m,S as q,i as n}from"./assets/vendor-BK_rxH-O.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();m.defaults.baseURL="https://pixabay.com/api/";async function y(r,e=1,i=15){try{return(await m.get("/",{params:{key:"51491215-b07c5a52c3d96c7bcc8c26318",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:i}})).data}catch(a){throw console.error("Error fetching images:",a),a}}let s=null;function C(r){return r.map(e=>`
      <li class="gallery-item">
        <div class="image-wrap">
          <a href="${e.largeImageURL}" data-lightbox="gallery" data-title="${e.tags}">
            <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          </a>
        </div>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${e.likes}</p>
          <p class="info-item"><b>Views</b> ${e.views}</p>
          <p class="info-item"><b>Comments</b> ${e.comments}</p>
          <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
        </div>
      </li>
    `).join("")}function P(r){r.innerHTML=""}function $(){return s||(s=new q(".gallery a",{captionsData:"alt",captionDelay:250})),s}function h(r,e){const i=C(e);r.insertAdjacentHTML("beforeend",i),s?s.refresh():s=$()}function b(){document.querySelector(".loader").style.display="block"}function w(){document.querySelector(".loader").style.display="none"}const L=document.querySelector(".form"),g=L.querySelector('input[name="search-text"]'),d=document.querySelector(".gallery"),p=document.querySelector(".load-page-btn");let f="",l=1;const c=15;function v(){p.style.display="block"}function S(){p.style.display="none"}L.addEventListener("submit",async r=>{r.preventDefault();const e=g.value.trim();if(e===""){n.warning({title:"",message:"Please enter something in the search field",position:"topRight",backgroundColor:"#ffa000",color:"white",progressBarColor:"#bb7b10",timeout:3e3});return}f=e,l=1,g.value="",P(d),b(),S();try{const a=(await y(f,l,c)).hits;a.length===0?n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",color:"white",progressBarColor:"#b51b1b",timeout:3e3}):(h(d,a),a.length===c&&v())}catch{n.error({title:"Error",message:"Сталася помилка при завантаженні зображень. Будь ласка, спробуйте пізніше.",position:"topRight",backgroundColor:"#ef4040;",color:"white",progressBarColor:"#b51b1b;",timeout:3e3})}finally{w()}});p.addEventListener("click",async()=>{l++,b(),S();try{const e=(await y(f,l,c)).hits;h(d,e,!1),e.length===c&&v()}catch{n.error({message:"Error loading more images.",position:"topRight",backgroundColor:"#ef4040",color:"white",progressBarColor:"#b51b1b",timeout:3e3})}finally{w()}});
//# sourceMappingURL=index.js.map
